version: '2'
services:
  web:
    image: registry.meerkats.com.au:5000/projects.meerkats.com.au-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      VIRTUAL_HOST: projects.meerkats.com.au, www.projects.meerkats.com.au

  node:
    image: registry.meerkats.com.au:5000/projects.meerkats.com.au-node:latest
